### ISSUE TITLE
No pshtt.zip file in 'develop' branch

### ISSUE THREAD

**Issue by refayathaque** [dhs-ncats/lambda_functions#29]
Hi guys,

Upon cloning the repo and running all commands in the readme I do not get the `pshtt.zip` file, however, once I switch into the `master` branch I do. Is there something different we need to do to build the `pshtt.zip` file using Docker in the `develop` branch?

Thank you,

**Comment by jsf9k** [comment]
@refayathaque, thanks for the issue.  Is this the error you're seeing?
```bash
/venv/bin/activate: line 31: $1: unbound variable
```

I ran into that myself today, and I created #32 to fix it.  Please let me know if this is the same issue you are seeing.

**Comment by jsf9k** [comment]
@refayathaque, #32 is now merged.  Give that a try and let us know if that fixes the issue you were seeing (or not).

**Comment by jsf9k** [comment]
I am going to close this issue since I believe it is fixed.  @refayathaque, please reopen it if I haven't fixed the problem you were seeing.

**Comment by refayathaque** [comment]
Hi @jsf9k 

Sorry I'm getting to this so late. Ummm I don't think we are talking about the same thing. So I am using this repo to build myself Lambda deployment packages for pshtt and trustymail. I'm not using this with `domain-scan`. Based on your instructions in the README, 'Building the environment zip files for all scanners and deploying them to AWS Lambda using domain-scan:', what I am having issues within the `develop` branch is step # 3, after running `docker-compose up` I am not seeing the pshtt.zip, trustymail.zip, and sslyze.zip files. However, once I run `docker-compose up` from the `master` branch I do see the .zip files.

It's not a massive issue but just wanted to bring it to your attention.

Thank you!

**Comment by jsf9k** [comment]
@refayathaque, the master branch is woefully out of date.  You really want to be building from the develop branch.  Can you share the output of `docker-compose build && docker-compose up` when you run it from the develop branch?

**Comment by refayathaque** [comment]
Hi Shane @jsf9k 

Attached are some screenshots that should explain what is going on. Appreciate the help!

![Screen Shot 2019-07-01 at 11 31 08 AM](https://user-images.githubusercontent.com/25051299/60464222-f2056280-9c1b-11e9-800b-87922a07b110.png)
![Screen Shot 2019-07-01 at 11 24 18 AM](https://user-images.githubusercontent.com/25051299/60464223-f2056280-9c1b-11e9-8bf6-ed648779ce0c.png)
![Screen Shot 2019-07-01 at 11 22 29 AM](https://user-images.githubusercontent.com/25051299/60464224-f29df900-9c1b-11e9-8db0-2dfe0b17de28.png)
![Screen Shot 2019-07-01 at 11 21 59 AM](https://user-images.githubusercontent.com/25051299/60464226-f29df900-9c1b-11e9-878c-7486e40f7587.png)

**Comment by jsf9k** [comment]
You should definitely be using the `develop` branch.  Thanks for the screenshots; I think I see the problem you're having.  I'll create a pull request now.

**Comment by jsf9k** [comment]
@refayathaque, can you check out branch `bugfix/fix_unbound_var_error` and let me know if it resolves your issue?  Thanks!

**Comment by refayathaque** [comment]
@jsf9k thank you so much! `docker-compose build` and `up` from `develop` branch yielding zip files! Also when you get a chance can you please have a look at trustymail, I still keep getting that darn **module 'DNS' has no attribute 'Type'** when I try to run it in Lambda (I've tried Python 2.7, 3.6 and also 3.7). https://github.com/cisagov/trustymail/issues/41#issuecomment-505608296
