### ISSUE TITLE
SSLyze within Trustymail

### ISSUE THREAD

**Issue by refayathaque** [dhs-ncats/lambda_functions#45]
Hi @jsf9k and @konklone !

I was wondering if you guys had plans to package SSLyze with trustymail. I am now using the [trustymail-lambda](https://github.com/cisagov/trustymail-lambda) to deploy my trustymail lambda functions, and I am able to run scans successfully. 

However, for me to be able to perform a complete BOD 18-01 check I'll need to use SSLyze to scan the SMTP servers trustymail finds under a domain. 

The pshtt-lambda actually has SSLyze bundled in, so I do not have this issue when doing BOD 18-01 web scans. I get the data from pshtt, use the Canonical URL pshtt returns to do SSLyze scans on the server. I am looking to do the same with trustymail. 

Right now, I am thinking about running two Lambdas, one running trustymail and the other running SSLyze on the same domain, but I would like to avoid this.

Best,

**Comment by jsf9k** [comment]
@refayathaque, we do not have plans to bundle sslyze with trustymail.  We run trustymail and sslyze separately via 18F/domain-scan, which is smart enough to do exactly what you mentioned - run sslyze against the trustymail findings.  I think that would be a great solution for you.

If you don't want to use 18F/domain-scan, it should be pretty simple to fork and modify this repo to meet your needs.  Just use the pshtt lambda as an example.

**Comment by refayathaque** [comment]
Hi @jsf9k ,

Thanks for getting back so soon, I appreciate that. :) I don't have much experience with `18F/domain-scan`, but does it have the ability for me to edit the lambda handler for it to do specifically what I need it to do? My entire infrastructure of scanning for BOD 18-01 and collecting data is reliant on Lambda and DynamoDB, and I'm not running anything in a headless mode on a box or locally.

Also, I'm noticing that there are some discrepancies between the trustymail lambda code in this repo and the one in the [lambda-trustymail](https://github.com/cisagov/trustymail-lambda) repo. 

Allow me to explain:

So when I use the docker commands to build myself a `trustymail_complete.zip` file in this repo with the handler provided from [lambda-trustymail](https://github.com/cisagov/trustymail-lambda) (I'm not making any changes to the handler) I get this error in Lambda:

![Screen Shot 2019-08-06 at 5 35 27 PM](https://user-images.githubusercontent.com/25051299/62579208-27334f00-b871-11e9-98be-a071fd6ab087.png)

Interestingly, when I build with docker from [lambda-trustymail](https://github.com/cisagov/trustymail-lambda) (handler here is identical to what is above) and upload the `trustymail.zip` I see no issues:

![Screen Shot 2019-08-06 at 5 45 12 PM](https://user-images.githubusercontent.com/25051299/62579517-fc95c600-b871-11e9-8ef1-3ad52e50bc30.png)

This is not a big deal as long as we have one working lambda for trustymail, but I really want to keep using this repo to build lambda functions as this is more recent than [lambda-trustymail](https://github.com/cisagov/trustymail-lambda) based on commits.

Just thought you guys should know.

Thanks,

**Comment by jsf9k** [comment]
The trustymail-lambda and sslyze-lambda repos are old and unsupported.  I'm sure they use ancient versions of the libraries they depend on.  You'll have to update those repos if you want to use them.

Note that the lambda handler is different for trustymail-lambda and sslyze-lambda that it is for lambda_functions.  You'll need to use one or the other; you can't mix-and-match.

**Comment by refayathaque** [comment]
@jsf9k I didn't see any lambda handlers for trustymail in this repo, that's why I copied over the handler in [lambda-trustymail](https://github.com/cisagov/trustymail-lambda). 

Ok, based off of what you're saying, I think it's best to refrain from using the `lambda-trustymail` and `lambda-sslyze` repos going forward. 

Can you point me to the handlers for trustymail and sslyze in this repo? 

I guess I'm seeing the error above in the AWS console is because of what you just mentioned...

**Comment by refayathaque** [comment]
A simple python shell script to create your own Lambda packages with the latest trustymail and sslyze:

```
import os

os.system('mkdir trustymail')
os.system('cd trustymail')
os.system('python3 -m venv venv')
os.system('source venv/bin/activate')
os.system('pip install --upgrade pip setuptools')
os.system('pip install --upgrade trustymail==0.7.5 --target .')
os.system('pip install --upgrade sslyze==2.1.3 --target .')
os.system('touch main.py')
# Edit the handler function before zipping
os.system('zip -r9 ~/Desktop/trustymail.zip .')
```

**Comment by refayathaque** [comment]
Hi @jsf9k ,

So I decided to build my own trustymail lambda function package bundled with sslyze. I did so by spinning up an Amazon Linux instance and building out my package there (steps similar to what I've posted above). I'm still using the handler function from [trustymail-lambda](https://github.com/cisagov/trustymail-lambda) as I can't find any other handler functions to go off of. I am not making any changes to this handler file and running on Lambda as is. The package has the latest version of trustymail (0.7.5). This is the error I am seeing:

```
[Errno 2] No such file or directory: 'cache/public-suffix-list.txt': FileNotFoundError
Traceback (most recent call last):
File "/var/task/main.py", line 100, in handler
smtp_ports, True, scan_types, dns_hostnames)
File "/var/task/trustymail/trustymail.py", line 721, in scan
domain = Domain(domain_name, timeout, smtp_timeout, smtp_localhost, smtp_ports, smtp_cache, dns_hostnames)
File "/var/task/trustymail/domain.py", line 66, in __init__
self.base_domain_name = get_public_suffix(self.domain_name)
File "/var/task/trustymail/domain.py", line 43, in get_public_suffix
public_list = get_psl()
File "/var/task/trustymail/domain.py", line 35, in get_psl
with open(PublicSuffixListFilename, encoding='utf-8') as psl_file:
FileNotFoundError: [Errno 2] No such file or directory: 'cache/public-suffix-list.txt'
```

This leads me to suspect that there is an issue with this part of the code in the handler:

```
import trustymail

# Monkey patching trustymail to make it cache the PSL where we
# want, and to make the PSL cache read-only.
trustymail.PublicSuffixListFilename = 'cache/public-suffix-list.txt'
trustymail.PublicSuffixListReadOnly = True

from trustymail.trustymail import scan
domain = scan(domain_name, timeout, smtp_timeout, smtp_localhost, smtp_ports, True, scan_types, dns_hostnames)
```

I don't really understand what you guys mean by 'Monkey patching trustymail to make it cache the PSL where we want, and to make the PSL cache read-only.'

Thank you for helping me with this, I feel like I am getting really close to being able to run the latest version of trustymail on Lambda!

**Comment by jsf9k** [comment]
The problem is that when you create the zip file you are missing [this step](https://github.com/cisagov/trustymail-lambda/blob/develop/build.sh#L45-L49).

Alternatively, you can remove the monkey patching code from the handler.  That code is there because otherwise the Lambda will download the public suffix list (PSL) every time it runs.  We found that when we ran the lambda hundreds of times, downloading the PSL each time, the PSL site would eventually start temporarily blocking us.

[Here is a link](https://en.wikipedia.org/wiki/Monkey_patch) describing what is meant by monkey patching.  It essentially means changing the behavior of software at runtime, without changing the source code.

**Comment by refayathaque** [comment]
@jsf9k !!! Thank you so much! We have the latest version of trustymail up and running! Below is what I did, and I hope it helps someone trying to run the latest trustymail on Lambda without domain-scan. :)

Building a custom trustymail and sslyze packaged on an Amazon Linux EC2 instance
* Instance name: trustymail
    * SHOULD HAVE A PUBLIC IP
    * Instance should be set up with python3/pip3 and other updates
        * Helpful links for python3/pip3
            * https://www.eukhost.com/forums/forum/technical-support/tutorials-how-tos/22616-how-to-install-zip-and-unzip-command-in-linux
            * https://www.tecmint.com/install-pip-in-linux/
* (You are in your new EC2 instance) Steps:
    * mkdir trustymail
    * cd trustymail
    * mkdir cache
    * wget -q -O cache/public-suffix-list.txt \ https://publicsuffix.org/list/public_suffix_list.dat
        * https://github.com/cisagov/trustymail-lambda/blob/develop/build.sh#L45-L49
    *  pip3 install --upgrade trustymail==0.7.5 --target .
        * Consult https://github.com/cisagov/trustymail/releases to check and use the latest release
    *  pip3 install --upgrade sslyze==2.1.3 --target .
        * Consult https://github.com/nabla-c0d3/sslyze/releases to check use the latest release
    * vi main.py
    * Hold down ‘d’ until all existing handler function code is deleted
    * Hit ‘i’ for INSERT mode then just paste in the new handler function code
        * Use sample below as a starting point for trustymail handler
        * https://github.com/cisagov/trustymail-lambda/blob/develop/lambda_handler.py
    * Hit ‘esc'
    * Type ‘:wq’ to save and quit out of vim
    * zip -r9 ../trustymail.zip .
    * cd ../
    * Move over to your local machine’s directory where you have the pem key saved (we’ll assume the pem key is `test.pem` and that it’s on your ~/Desktop)
        * You are not interfacing with the EC2 instance anymore
    *  scp -i test.pem ec2-user@00.000.000.0:~/trustymail.zip .
        * (You are securely copying the trustymail.zip from the EC2 instance to your local machine)
        * https://medium.com/@dearsikandarkhan/files-copying-between-aws-ec2-and-local-d07ed205eefa
    * Trustymail.zip is in ~/Desktop and ready to be deployed to Lambda using the console

You could encounter the error "Unable to import module 'main': No module named '_cffi_backend’” when trying to run sslyze in Lambda
* "For python 3.6, when I encountered the error "Unable to import module 'main': No module named '_cffi_backend'" in an AWS Lambda Function, I was able to run mv _cffi_backend.cpython-36m-x86_64-linux-gnu.so _cffi_backend.so in my linux docker image with virtualenv and the issue was resolved. Like mentioned above, some dependencies might be better placed with --target, to get them where you need them" - https://stackoverflow.com/questions/53583089/lambda-error-no-module-found-cryptography-hamtaz-bindings-constant-time
  * If _cffi_backend.cpython-36m-x86_64-linux-gnu.so is not your directory you might want to run:
    * sudo pip3 install --upgrade cffi --target .
    * sudo pip3 install --upgrade cryptography --target .

**Comment by jsf9k** [comment]
Great news, @refayathaque!

**Comment by refayathaque** [comment]
@jsf9k thank you! Glad to have trusty mail up and running. We are now trying to use SSLyze to extract data from these email servers to see if they have weak cryptographic ciphers and deprecated network security protocols. But unfortunately, we cannot seem to be able to establish connections with these servers without there being a timeout or some other error. Do you have any experience with using SSLyze in trying to connect to federal email servers?

**Comment by jsf9k** [comment]
@refayathaque When evaluating mail servers with sslyze, it's important to:
1. Specify the port (probably 25, 465, or 587)
2. Use the `--starttls=smtp` command line option

So your command line would be something like:
```
sslyze --starttls=smtp --sslv2 --sslv3 --tlsv1 --tlsv1_1 --tlsv1_2 --tlsv1_3 dhs-gov.mail.protection.outlook.com:25 
```

Does that help?

**Comment by refayathaque** [comment]
Hi @jsf9k , thank you so much for your help. We are using SSLyze in a Lambda function to do the scans. I am explicitly declaring if STARTTLS is needed and I am also explicitly providing a port number. Our Lambda code below:

`def handler(event, context):
    # Extract some variables from the event dictionary
    hostname = event['domain_name']

    protocol = TlsWrappedProtocolEnum.PLAIN_TLS
    if event['starttls_smtp']:
        protocol = TlsWrappedProtocolEnum.STARTTLS_SMTP

    # Run one scan command to list the server's TLS 1.0 cipher suites
    try:
        print('Attempting connection to: ', hostname)
        if event['port']:
            print('Port provided, port: ', port)
            print('protocol: ', protocol)
            server_tester = ServerConnectivityTester(
                hostname=hostname,
                tls_wrapped_protocol=protocol,
                port=event['port']
            )
        else:
            print('Port NOT provided, defaulting to 443')
            print('protocol: ', protocol)
            server_tester = ServerConnectivityTester(
                hostname=hostname,
                tls_wrapped_protocol=protocol
            )
        print('server_tester: ', server_tester)
        print(f'\nTesting connectivity with {server_tester.hostname}:{server_tester.port}...')
        server_info = server_tester.perform(
            network_timeout=30
        )
        print(server_info)
    except ServerConnectivityError as e:
        # Could not establish an SSL connection to the server
        print('e: ', e)
        raise RuntimeError(f'Could not connect to {e.server_info.hostname}: {e.error_message}')

    command = Tlsv10ScanCommand()

    synchronous_scanner = SynchronousScanner()

    scan_result = synchronous_scanner.run_scan_command(server_info, command)
    for cipher in scan_result.accepted_cipher_list:
        print(f'    {cipher.name}')
    print('scan_result: ', scan_result)`

**Comment by refayathaque** [comment]
Some screenshots:

<img width="1602" alt="Screen Shot 2019-08-27 at 8 25 09 PM" src="https://user-images.githubusercontent.com/25051299/63885505-808d2a80-c9a6-11e9-8d4c-0aa0da0c1b23.png">
<img width="1602" alt="Screen Shot 2019-08-27 at 8 41 19 PM" src="https://user-images.githubusercontent.com/25051299/63885510-82ef8480-c9a6-11e9-921b-779829f61a86.png">

@jsf9k sorry I uploaded the wrong screenshots before!

**Comment by jsf9k** [comment]
@refayathaque, the screenshot with an error doesn't indicate a timeout.  I think it indicates something is missing from your sslyze lambda package.

Another thing to be aware of is that AWS throttles port 25 traffic by default.  You can remove the throttling by submitting [this form](https://aws.amazon.com/forms/ec2-email-limit-rdns-request) when logged in with the root AWS credentials for your account.
