### ISSUE TITLE
Document commands to rebuild image?

### ISSUE THREAD

**Issue by konklone** [dhs-ncats/lambda_functions#7]
My `docker-compose up build_sslyze` command was consistently rebuilding an `sslyze.zip` that included SSLyze v1.3.4, even though https://github.com/dhs-ncats/lambda_functions/commit/71277f6ccc1357d3fd385141d4b8d38a86dda5c9 updated it to not do so.

I then ran `docker-compose build build_sslyze`, and then re-ran `docker-compose up build_sslyze`, and that worked.

I'm not super Docker-fluent, but should this be part of the documented instructions?

**Comment by jsf9k** [comment]
The `Dockerfile` copies the build script into the container, so when that script updates you have to rebuild the container.  This is pretty standard `docker-container` stuff, but some simple instructions would be a good idea.  I'll create some.

**Comment by jsf9k** [comment]
This issue is resolved by #8.
